language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support-22.2.1
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - ./gradlew clean build check

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
